version: '3.9'

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: document_service
    ports:
      - "5431:5432"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
  
  vecdb:
    image: chromadb/chroma:latest
    container_name: vecdb
    restart: always
    ports:
      - "8080:8000"
    volumes:
      - chroma-data:/chroma/chroma
  
  doc-service:
    build: ./document_service
    container_name: doc-service
    ports:
      - "6060:6060" 
    env_file:
      - ./document_service/.env
    depends_on:
      - postgresdb
      - vecdb

  rag-service:
    build: ./rag_service
    container_name: rag-service
    ports:
      - "7000:7000"
    env_file:
      - ./rag_service/.env
    depends_on:
      - vecdb

  frontend-service: 
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - doc-service
      - rag-service

volumes:
  postgresdb-data:
  chroma-data: